// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iipxmbcrnohooieyrucs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcHhtYmNybm9ob29pZXlydWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODQyODEsImV4cCI6MjA1ODQ2MDI4MX0.z4_eERYUHNQ5pTakagkfEOefRohyaDFXCNE_uGNZrbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);